name: Automerge Release
on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # ratchet:tibdex/github-app-token@v1.8.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.APP_INSTALL_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584" # ratchet:pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs['token'] }}
          MERGE_DELETE_BRANCH: true
          MERGE_LABELS: auto-release
          MERGE_REMOVE_LABELS: auto-release
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 30000 # 30 seconds
