name: Update Terraform Docs
on:
  push:
    branches:
      - "renovate/**"
permissions:
  contents: read
jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ secrets.DOCUMENTATION_APP_ID }}
          private-key: ${{ secrets.DOCUMENTATION_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Run terraform-docs
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # ratchet:terraform-docs/gh-actions@v1
        with:
          output-method: inject
          git-push: "true"
          recursive: true
          git-commit-message: "docs: update terraform docs following renovate patch"
