name: Update Terraform Docs
on:
  push:
    branches:
      - "renovate/**"
permissions:
  contents: write
jobs:
  terraform-docs:
    uses: batinicaz/gha/.github/workflows/terraform-docs.yml@v1
    with:
      recursive: true
    secrets:
      DOCUMENTATION_APP_ID: ${{ secrets.DOCUMENTATION_APP_ID }}
      DOCUMENTATION_PRIVATE_KEY: ${{ secrets.DOCUMENTATION_PRIVATE_KEY }}
