name: Lint & Plan
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!main"
permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run pre-commit
        uses: batinicaz/gha/.github/actions/pre-commit@v1
  terraform:
    uses: batinicaz/gha/.github/workflows/terraform-plan.yml@v1
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    with:
      working_directory: "."
      infisical_project_env: terraform-oci-core
    secrets:
      INFISICAL_IDENTITY_ID: ${{ vars.INFISICAL_IDENTITY_ID }}
