name: Create Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    uses: batinicaz/gha/.github/workflows/release.yml@dbabbc3d5f938c9778cf59c73438717c35ab5988 # ratchet:batinicaz/gha/.github/workflows/release.yml@v1.2.10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
