name: Create Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    uses: batinicaz/gha/.github/workflows/release.yml@9c3c1068166c7e5df0905f27264680b1bfda64a1 # ratchet:batinicaz/gha/.github/workflows/release.yml@v1.2.10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
