name: Pre-commit Cache
on:
  push:
    branches: [main]
    paths: [".pre-commit-config.yaml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: batinicaz/gha/.github/actions/pre-commit@v1
