name: Pre-commit Cache
on:
  push:
    branches: [main]
    paths: [".pre-commit-config.yaml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: batinicaz/gha/.github/actions/pre-commit@v1
