name: Deploy Tags
run-name: "Deploy ${{ github.ref }}"
on:
  push:
    tags:
      - "v**"
permissions:
  contents: read
jobs:
  deploy:
    uses: batinicaz/gha/.github/workflows/terraform-apply.yml@4b734bf625f979b9a8bfd694ff95c5c3ab62d3f0 # ratchet:batinicaz/gha/.github/workflows/terraform-apply.yml@v1.2.10
    permissions:
      contents: read
      id-token: write
    with:
      working_directory: "."
      infisical_project_env: terraform-oci-core
    secrets:
      INFISICAL_IDENTITY_ID: ${{ vars.INFISICAL_IDENTITY_ID }}
