name: Deploy Tags
run-name: "Deploy ${{ github.ref }}"
on:
  push:
    tags:
      - "v**"
permissions:
  contents: read
jobs:
  deploy:
    uses: batinicaz/gha/.github/workflows/terraform-apply.yml@836e78da181c617999d83875e58f6fe7ca008f53 # v1
    permissions:
      contents: read
      id-token: write
    with:
      working_directory: "."
      infisical_project_env: terraform-oci-core
    secrets:
      INFISICAL_IDENTITY_ID: ${{ vars.INFISICAL_IDENTITY_ID }}
